package app.cloudmoji.android.data

import kotlinx.serialization.Serializable

/**
 * Wire format of `assets/EmojiData.json`, generated by
 * `tools/generate-android-data` from the TypeScript source of truth under
 * `src/data/`. These types exist only to decode the file exactly as shipped
 * — [EmojiRepository] is the API everything else in the app uses.
 *
 * Field shapes intentionally match the JSON key-for-key. Every field is
 * required (no defaults) except [animalSounds], which iOS also decodes as
 * optional so a file generated before that key existed still loads, and
 * [CountableDto.enPlural], which is genuinely absent for most entries. Any
 * other missing or unrecognised key is a decode error — see
 * [EmojiRepositoryLoader]'s `Json` configuration — because silently accepting
 * schema drift between the generator and this port is worse than a loud
 * crash.
 */
@Serializable
internal data class EmojiDataDto(
    val version: Int,
    val languages: List<LanguageMetaDto>,
    val categories: List<CategoryTabDto>,
    val emojis: List<EmojiEntryDto>,
    val countables: List<CountableDto>,
    /** Keyed by language code; ten entries each, for counts 1...10. */
    val numberWords: Map<String, List<String>>,
    /** Glyph -> language code -> what that animal says. */
    val animalSounds: Map<String, Map<String, String>>? = null,
)

@Serializable
internal data class LanguageMetaDto(
    val id: String,
    val short: String,
    val name: String,
    val speech: String,
    val voicePrefixes: List<String>,
)

@Serializable
internal data class CategoryTabDto(
    val id: String,
    val icon: String,
    val labels: Map<String, String>,
)

@Serializable
internal data class EmojiEntryDto(
    val emoji: String,
    val cat: String,
    val en: String,
    val zh: String,
    val ms: String,
    val ja: String,
    val tl: String,
)

@Serializable
internal data class CountableDto(
    val emoji: String,
    val en: String,
    val enPlural: String? = null,
    val zh: String,
    val ms: String,
    val ja: String,
    val tl: String,
)
